name: Surface-Lock Checks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools (jq, tidy, curl, node)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq tidy
          sudo apt-get install -y nodejs npm

      - name: Validate required files exist
        run: |
          required=(
            ".nojekyll"
            "index.html"
            "_health/index.html"
            "_health/index.json"
            "_audit/dom.html"
            "_audit/manifest.json"
            "_audit/css.hash"
          )
          missing=0
          for f in "${required[@]}"; do
            if [ ! -f "$f" ]; then
              echo "::error file=$f::Required file missing: $f"
              missing=1
            fi
          done
          test $missing -eq 0

      - name: Validate JSON syntax
        run: |
          set -e
          jq empty _health/index.json
          jq empty _audit/manifest.json

      - name: Validate HTML syntax (non-fatal warnings)
        run: |
          tidy -errors -q index.html || true
          tidy -errors -q _health/index.html || true
          tidy -errors -q _audit/dom.html || true

      - name: Start local server
        run: |
          python3 -m http.server 8000 &>/dev/null &
          sleep 2

      - name: Sanity check local endpoints (HTTP 200)
        run: |
          set -e
          for url in \
            "http://localhost:8000/" \
            "http://localhost:8000/_health/" \
            "http://localhost:8000/_audit/dom.html" \
            "http://localhost:8000/_audit/manifest.json" \
            "http://localhost:8000/_audit/css.hash" \
          ; do
            code=$(curl -sS -o /dev/null -w "%{http_code}" "$url")
            if [ "$code" != "200" ]; then
              echo "::error ::$url returned $code"
              exit 1
            fi
          done

      # Optional link crawl of the local build (non-fatal)
      - name: Broken link check (optional)
        run: |
          npx --yes broken-link-checker http://localhost:8000 -ro --filter-level=3 || true
