name: Surface-Lock Checks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools (jq, tidy, curl, node)
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y jq curl python3
          # HTML Tidy package on GitHub runners:
          sudo apt-get install -y tidy-html5 || true
          # Node only if we run the optional link crawl
          sudo apt-get install -y nodejs npm || true

      - name: Validate required files exist
        run: |
          set -e
          required=("index.html" ".nojekyll" "manifest.json" "dom.html" "css.hash" "healthindex.html" "healthindex.json")
          missing=0
          for f in "${required[@]}"; do
            if [ ! -f "$f" ]; then
              echo "::error file=$f::Required file missing: $f"
              missing=1
            fi
          done
          test $missing -eq 0

      - name: Validate JSON syntax
        run: |
          set -e
          jq empty manifest.json
          jq empty healthindex.json

      - name: Validate HTML syntax (non-fatal)
        run: |
          # Tidy may not exist on some runners; don’t fail the job on warnings.
          if command -v tidy >/dev/null 2>&1; then
            tidy -errors -q index.html         || true
            tidy -errors -q dom.html           || true
            tidy -errors -q healthindex.html   || true
          else
            echo "tidy not available; skipping HTML lint."
          fi

      - name: Start local server
        run: |
          python3 -m http.server 8000 >/dev/null 2>&1 &
          for i in {1..20}; do
            if curl -sSf http://localhost:8000/ >/dev/null; then exit 0; fi
            sleep 0.3
          done
          echo "Server did not come up in time" >&2
          exit 1

      - name: Sanity check local endpoints (HTTP 200)
        run: |
          set -e
          curl -sS -o /dev/null -w "%{http_code}\n" http://localhost:8000/                  | grep -q "^200$"
          curl -sS -o /dev/null -w "%{http_code}\n" http://localhost:8000/healthindex.html  | grep -q "^200$"
          curl -sS -o /dev/null -w "%{http_code}\n" http://localhost:8000/dom.html          | grep -q "^200$"
          test -f css.hash
          test -f manifest.json

      # Optional link crawl (non-fatal)
      - name: Broken link check (optional)
        run: |
          npx --yes broken-link-checker http://localhost:8000 -ro --filter-level=3 || true
