name: Link Check

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Lychee link checker
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          # checks all files in the repo; you can narrow later (e.g., "./index.html ./manifest.json")
          args: --verbose .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
